"""second migration

Revision ID: 41f26516b94d
Revises: 
Create Date: 2026-06-28 20:25:07.632338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '41f26516b94d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borehole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_depth', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('critical_low_level', sa.Float(), nullable=False),
    sa.Column('optimal_high_level', sa.Float(), nullable=False),
    sa.Column('soil_characteristic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('water_body_proximity', sa.Float(), nullable=False),
    sa.Column('topography', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('predicted_recharge_rate', sa.Float(), nullable=False),
    sa.Column('predicted_abstraction_volume', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ON', 'OFF', name='pumpstatus'), nullable=False),
    sa.Column('power_rating', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('last_status_change', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAULTY', name='sensorstatus'), nullable=False),
    sa.Column('type', sa.Enum('PRESSURE_TRANSDUCER', 'FLOW_METER', 'ESP32', name='sensortype'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('raw_reading', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('calculated_flow_rate', sa.Float(), nullable=False),
    sa.Column('cummulative_volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('TURNED_ON', 'TURNED_OFF', name='pumpaction'), nullable=False),
    sa.Column('triggered_by', sa.Enum('AUTOMATIC_SCHEDULE', 'MANUAL_OVERRIDE', 'CRITICAL_SAFETY', name='pumptrigger'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=True),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('days_of_the_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='daysoftheweek'), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'CANCELLED', 'COMPLETED', name='schedulestatus'), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_level_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('raw_reading', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('calculated_water_depth', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_level_reading')
    op.drop_table('schedule')
    op.drop_table('pump_history')
    op.drop_table('flow_reading')
    op.drop_table('sensor')
    op.drop_table('pump')
    op.drop_table('prediction')
    op.drop_table('weather')
    op.drop_table('borehole')
    op.drop_table('location')
    op.drop_table('user')
    # ### end Alembic commands ###
