"""rename raw_reading to water_level on WaterLevelReading and makes some field nullable on WaterLevelReading and FlowReading

Revision ID: 4ed591d939dd
Revises: b6bf48633cc0
Create Date: 2026-07-04 04:43:04.901243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed591d939dd'
down_revision: Union[str, Sequence[str], None] = 'b6bf48633cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_reading', 'calculated_flow_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('flow_reading', 'cummulative_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('water_level_reading', sa.Column('water_level', sa.Float(), nullable=False))
    op.alter_column('water_level_reading', 'calculated_water_depth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('water_level_reading', 'raw_reading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_level_reading', sa.Column('raw_reading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('water_level_reading', 'calculated_water_depth',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('water_level_reading', 'water_level')
    op.alter_column('flow_reading', 'cummulative_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('flow_reading', 'calculated_flow_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
