"""remove unuse fields from FlowReading and WaterLevelReading, rename raw_reading to abstraction_rate

Revision ID: 645e66351f3f
Revises: b78628891a33
Create Date: 2026-07-20 04:58:07.642434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645e66351f3f'
down_revision: Union[str, Sequence[str], None] = 'b78628891a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_reading', sa.Column('abstraction_rate', sa.Float(), nullable=False))
    op.drop_column('flow_reading', 'raw_reading')
    op.drop_column('flow_reading', 'cummulative_volume')
    op.drop_column('flow_reading', 'calculated_flow_rate')
    op.drop_column('water_level_reading', 'calculated_water_depth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_level_reading', sa.Column('calculated_water_depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flow_reading', sa.Column('calculated_flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flow_reading', sa.Column('cummulative_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flow_reading', sa.Column('raw_reading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('flow_reading', 'abstraction_rate')
    # ### end Alembic commands ###
