"""made sensor_id and captured_at unique on both waterlever and flowreading model

Revision ID: 8a9ff9596bf8
Revises: f529ba354a7e
Create Date: 2026-08-12 19:09:25.608910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9ff9596bf8'
down_revision: Union[str, Sequence[str], None] = 'f529ba354a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_flow_sensor_captured', 'flow_reading', ['sensor_id', 'captured_at'])
    op.create_unique_constraint('uq_water_level_sensor_captured', 'water_level_reading', ['sensor_id', 'captured_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_water_level_sensor_captured', 'water_level_reading', type_='unique')
    op.drop_constraint('uq_flow_sensor_captured', 'flow_reading', type_='unique')
    # ### end Alembic commands ###
