"""add device_key field to sensor model

Revision ID: 8e7359856e70
Revises: c29911d8320c
Create Date: 2026-07-02 18:26:38.027017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e7359856e70'
down_revision: Union[str, Sequence[str], None] = 'c29911d8320c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'device_key')
    # ### end Alembic commands ###
