"""Add field to WaterLevelReading and FlowReading

Revision ID: c43306740d12
Revises: f02428d03bb1
Create Date: 2026-08-10 21:38:40.485444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43306740d12'
down_revision: Union[str, Sequence[str], None] = 'f02428d03bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "flow_reading",
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "water_level_reading",
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("UPDATE flow_reading SET captured_at = created_at")
    op.execute("UPDATE water_level_reading SET captured_at = created_at")

    op.alter_column("flow_reading", "captured_at", nullable=False)
    op.alter_column("water_level_reading", "captured_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_level_reading', 'captured_at')
    op.drop_column('flow_reading', 'captured_at')
    # ### end Alembic commands ###
